// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficCrash.Models;

namespace TrafficCrash.Migrations
{
    [DbContext(typeof(TrafficCrashContext))]
    [Migration("20191202034928_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrafficCrashVehicles.TrafficCrashVehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area12_I")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CrashDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CrashUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstContactPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicPlateState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maneuver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OccupantCnt")
                        .HasColumnType("bigint");

                    b.Property<string>("RdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TravelDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UnitNo")
                        .HasColumnType("bigint");

                    b.Property<string>("UnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDefect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleUse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrafficCrashVehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
