// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TrafficCrash;
//
//    var trafficCrashPeople = TrafficCrashPeople.FromJson(jsonString);

namespace TrafficCrashPeoples
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TrafficCrashPeople
    {
        [JsonProperty("person_id")]
        public string PersonId { get; set; }

        [JsonProperty("person_type")]
        public string PersonType { get; set; }

        [JsonProperty("rd_no")]
        public string RdNo { get; set; }

        [JsonProperty("vehicle_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long VehicleId { get; set; }

        [JsonProperty("crash_date")]
        public DateTimeOffset CrashDate { get; set; }

        [JsonProperty("sex")]
        public string Sex { get; set; }

        [JsonProperty("safety_equipment")]
        public string SafetyEquipment { get; set; }

        [JsonProperty("airbag_deployed")]
        public string AirbagDeployed { get; set; }

        [JsonProperty("ejection")]
        public string Ejection { get; set; }

        [JsonProperty("injury_classification")]
        public string InjuryClassification { get; set; }

        [JsonProperty("driver_action")]
        public string DriverAction { get; set; }

        [JsonProperty("driver_vision")]
        public string DriverVision { get; set; }

        [JsonProperty("physical_condition")]
        public string PhysicalCondition { get; set; }

        [JsonProperty("bac_result")]
        public string BacResult { get; set; }
    }

    public partial class TrafficCrashPeople
    {
        public static TrafficCrashPeople[] FromJson(string json) => JsonConvert.DeserializeObject<TrafficCrashPeople[]>(json, TrafficCrashPeoples.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TrafficCrashPeople[] self) => JsonConvert.SerializeObject(self, TrafficCrashPeoples.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
